e_bam_ref_data:
    resource: "@eBAMRefDataBundle/Resources/config/routing.yml"
    prefix:   /

e_bamiban_service:
    resource: "@eBAMIBANServiceBundle/Resources/config/routing.yml"
    prefix:   /

e_bam_object_mgt:
    resource: "@eBAMObjectMgtBundle/Resources/config/routing.yml"
    prefix:   /
