<?php

namespace eBAM\RefDataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CountryCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryCodeRepository extends EntityRepository
{
}
